env:
  global:
    - FRAMEWORK_NAME=RxApollo
    - secure: "IVdTuXiwER2aiRZu9hRMfjhckrw08ddcxfHsTyPW5yOSHdCOU/g37qV27OoGCK0xWY4HayuDSqHjdIky0HCCKoARGHZKcjcZCUnEarxTk5e9GuZ7NRfyKbSCDMwl0onqjuuGyJu3fLIM8ArCFiJrtVreRqkf49wEPE1yoyeNjDAY5RNSyKUGRJtfTVtiyZQf5Z6raVyEKBFMDR8TYXy4xBDU5ieaJS9i9E/d3F/x4X0Gc9g5P5kw9o0Sj5vGXR3e06LpXXtzi28cJsXRxGcayAfo0gpLKFjo+2fseJZVhWohTH8q9bNOaqd6gu3luXdjJZwkUC0+r/zGF1H35i08CS5o0EI3HqSgZgTpcPE3KgfWbgb+1a7ntzDrsBtvZS3KrH8hHDYBv1HCxwDQdVJO+7HoMacZRBAEWQmw0GvyDhl5tmLWfYsXYvDMLN7ndn3xUtWSR3FMhYjKApupeNb9DyKCRpeDGTBP8bbEtLE8J/VQPhwwK78OzgMV+LwRWQ4fihKmbTiwyOMTDpXqriKgecitH/pmDVBXR5bSSk1YQHM5xqfz1An4wxYlM2BskvIrLX0nnnRjhgtSEfRdieasohPyJHAwb0GgmOYN5QZ4hoNICIGWYHVobEdoZWnsgvhGaOHDGE7P+gbYbSkUjP6KTbCAHH/T1jlH0R9D0+IcpwQ="

cache:
  directories:
    - build
    - Packages
    - Carthage

script: placeholder # workaround for https://github.com/travis-ci/travis-ci/issues/4681
matrix:
  include:
    - script:
        - carthage bootstrap --platform ios --cache-builds
        - set -o pipefail && xcodebuild -scheme $FRAMEWORK_NAME -project $FRAMEWORK_NAME.xcodeproj clean build-for-testing test | xcpretty
      env: JOB=Xcode
      os: osx
      osx_image: xcode8.3
      language: objective-c
      before_install:
        - ./scripts/upstall-carthage.sh
        - ./scripts/upstall-swiftlint.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      before_deploy:
        - carthage build --no-skip-current
        - carthage archive $FRAMEWORK_NAME
    - script:
        - swift test
      env: JOB=SPM
      os: osx
      osx_image: xcode8.2
      language: objective-c
#    - script:
#        - swift test
#      env: JOB=Linux
#      sudo: required
#      dist: trusty
#      language: generic
#      install:
#        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"

  exclude:
    - script: placeholder # workaround for https://github.com/travis-ci/travis-ci/issues/4681

deploy:
  provider: releases
  api_key:
    secure: JVMI8VRlw0naEi3KcQgU+hqLB0L0FdeqLBCHAetjDeqhKqAGkjiKc+JaHqbt24KK64Bny+WwMle/4o3BgYo38W7fim8vIq+15PdR426cY2TyTSFH7EzY/gRta5ljvkR8R8YN/pYRlZR829mDKdUB7nEIS6bNY9t9bVn3gfn6Qg1rB3GsNjOlkoVKidPGAMEwTG0sScfkgi9v0yLIvOuf76ZWhWP1knPpw/HEiUNg20okRmnXqy0hLH3u2TTT63x0XEDK6eJyJo/MbN+O0oA2AFk96ZxVutanwE6Vud0oTT1YOzaGhkkr7iQRDBmP4/dJDfJ37KjqSjL+t6W8/Zv+i3ydKhqqDXPEC6bryLGwbL+MDWXmqCEi1EhXGlf9B1Zg/ozpZfR0MVJhj+Cgq5QYkD+MrWlFM8F/QEnr/dywXh6Q6QCDSsQOPIDVNavUB9A3gqD3+ZEh37P+9uIS2W4ejcqKj53bG9QwIPGY/ej1cwo88huTk8Mv04LXcLxedPEj0COU3aVIxN3D5Y74BwHOcMvl2hTKcz54hUr2j4tJ1JVz/eBg9QMpMkjhXn4XmxsZ80qbPqpDbAxOnqNXD5gzYhhYp+mzWTu6/enS/zBRbeb66oe5Y9KXFtXucf56IfU+3+OoI9xMhnu+mBnN12uFJ4ugn5mXl1F4jUeJSWqHcVQ=
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: scottrhoyt/$FRAMEWORK_NAME
    tags: true
    condition: $JOB = Xcode
